/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package combobox.java.frame;

import javax.swing.JOptionPane;

/**
 *
 * @author Documentos
 */
public class comboboxFrame extends javax.swing.JFrame {
    /**
     * Creates new form comboboxFrame
     */
    
    /*  Componente JComboBox (caixa de combinação), Biblioteca Swing, interface gráfica,
    *   combina um campo de texto editável [JComboBox.setEditable(True)] e uma lista suspensa para 
    *   que o utilizador possa selecionar um item de uma lista ou inserir um valor personalizado.
    *
    *   saiba mais sober os principais métodos da jcombobox em: https://github.com/lucasdepaulagailhardo-crypto/combobox-java-frame
    */ 
    public comboboxFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bntNova = new javax.swing.JButton();
        txtNova = new javax.swing.JTextField();
        cbCores = new javax.swing.JComboBox<>();
        bntRemover = new javax.swing.JButton();
        txtResultado = new javax.swing.JLabel();
        bntExibir = new javax.swing.JButton();
        bntEditableCbCores = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ComBox / Caixa de combinação");

        bntNova.setText("Nova");
        bntNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNovaActionPerformed(evt);
            }
        });

        cbCores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Vermelho", "Verde", "Paris" }));

        bntRemover.setText("Remover");
        bntRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRemoverActionPerformed(evt);
            }
        });

        txtResultado.setText("Resultado");
        txtResultado.setToolTipText("");

        bntExibir.setText("Exibir");
        bntExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExibirActionPerformed(evt);
            }
        });

        bntEditableCbCores.setText("Editable");
        bntEditableCbCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditableCbCoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bntNova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNova, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(bntExibir))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbCores, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bntEditableCbCores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtResultado)
                                .addGap(11, 11, 11)))))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado)
                    .addComponent(bntEditableCbCores))
                .addGap(40, 40, 40)
                .addComponent(txtNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntNova)
                    .addComponent(bntRemover)
                    .addComponent(bntExibir))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNovaActionPerformed
        // TODO add your handling code here:
        
        if (!txtNova.getText().isEmpty())
        cbCores.addItem(txtNova.getText());//Adiciona um novo item à comboBox a partir do texto do labelField (txtNova)
        //Não é necessário converter txtNova para String, pois estamos pegando o própria String do getText
        
        else JOptionPane.showMessageDialog(null, "Não há texto");
        
        txtNova.setText("");//Limpa a caixa de texto
    }//GEN-LAST:event_bntNovaActionPerformed

    private void bntRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRemoverActionPerformed
        // TODO add your handling code here:

        //Remove o item a partir da posição index (lista), inicia na posição 0
        //cbCores.removeItemAt(int index); /*comando exemplo*/
       
        cbCores.removeItem(cbCores.getSelectedItem());//Remove o item selecionado atual da ComoBox (index = 0)
    }//GEN-LAST:event_bntRemoverActionPerformed

    private void bntExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExibirActionPerformed
        // TODO add your handling code here:
        
        txtResultado.setText(cbCores.getSelectedItem().toString());//Set o texto do item atual (index = 0) da ComoBox no label Resultado
        //Os itens da jcombobox são definidos como objetos, logo modificamos para toString()
    }//GEN-LAST:event_bntExibirActionPerformed

    private void bntEditableCbCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditableCbCoresActionPerformed
        // TODO add your handling code here:
        cbCores.setEditable(true);//Habilita edição de texto da ComboBox
    }//GEN-LAST:event_bntEditableCbCoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comboboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comboboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comboboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comboboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comboboxFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEditableCbCores;
    private javax.swing.JButton bntExibir;
    private javax.swing.JButton bntNova;
    private javax.swing.JButton bntRemover;
    private javax.swing.JComboBox<String> cbCores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNova;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
